name: "CD: GitHub Pages"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  github-pages:
    name: "GitHub Pages"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Configure: Git"
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: "Toolchain: Python"
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: "Toolchain: ghp-import"
        run: pip3 install ghp-import
      - name: "Install"
        run: npm ci
      - name: "Build"
        run: npm run build
      - name: Deploy
        run: ghp-import build -p
        